# versão padrão dos templates CloudFormation
AWSTemplateFormatVersion: "2010-09-09"

# descrição da stack, para fins de documentação
Description: >
  Essa stack é usada para a criação da imagem base para o servidor web.
  Essa imagem será usada para definir o launch configuration do servidor
  para o auto scaling.

# recursos a serem criados
Resources:

  # define a nuvem privada virtual
  WordpressVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'

  # define uma subrede dentro da VPC
  WordpressSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref WordpressVPC
      CidrBlock: '10.0.0.0/24'

  # define o keypair de acesso às instâncias EC2
  WordpressKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: admin-keypair

